#!/bin/sh /etc/rc.common
# Copyright (C) 2014-2999 extgui.com
# Author bywayboy<bywayboy@qq.com>
# Last Update: 2014-09-22

START=90

EXECUTEBIN="/usr/sbin/vlmcsd"
PIDFILE="/var/run/vlmcsd.pid"
INIFILE="/etc/vlmcsd.ini"
CONFIGFILE=""
LISTENPORT=1688

start ()
{
	if [ ! -f $PIDFILE ]; then 
		$EXECUTEBIN -i $INIFILE -p $PIDFILE -P $LISTENPORT -l syslog
	else
		PID=`cat $PIDFILE`
		kill -s 0 $PID
		RESULT=$?
		if [ -f $PIDFILE ] && [ $RESULT -eq 0 ]; then
			echo "KMS Server is already running"
			exit 2
		else
			echo "Please check pid file or use forcestart to overwrite pid"
		fi
	fi
}

stop ()
{
	if [ -f $PIDFILE ]; then
		PID=`cat $PIDFILE`
		kill $PID
		rm $PIDFILE
		echo "KMS Has been stopped"
		exit 0
	else
		echo "KMS is not running"
		exit 1
	fi
}

restart ()
{

}
